// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using code_first_approch.MyDbContext;

#nullable disable

namespace code_first_approch.Migrations
{
    [DbContext(typeof(MyDataBaseContext))]
    [Migration("20260131015441_insertingdata")]
    partial class insertingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("code_first_approch.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "India",
                            DateOfBirth = new DateTime(2026, 1, 31, 7, 24, 41, 557, DateTimeKind.Local).AddTicks(671),
                            Email = "Admin@gmail.com",
                            Name = "Admin",
                            Password = "Admin@123",
                            PhoneNumber = 1234567890L,
                            gender = "male"
                        },
                        new
                        {
                            Id = 2,
                            Address = "India2",
                            DateOfBirth = new DateTime(2026, 1, 31, 7, 24, 41, 557, DateTimeKind.Local).AddTicks(699),
                            Email = "Admin2@gmail.com",
                            Name = "Admi2n",
                            Password = "Admin2@123",
                            PhoneNumber = 12234567890L,
                            gender = "male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
